apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demox
    app.kubernetes.io/part-of: demox
  name: demox
  namespace: application-service
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demox
    weight: 100
status: {}
